---
- name: Securely create a Linux user with Vault password
  hosts: all
  become: yes
  vars_files:
    - user_secrets.yml

  tasks:
    - name: Create a user with a Vault-encrypted password
      user:
        name: "{{ secure_user }}"
        password: "{{ secure_password }}"
        shell: /bin/bash
        state: present
